#!/usr/bin/env bash

# Install dotfiles using stow
STOW_FOLDERS=("tmux" "neovim" "LuaSnippets" "bash")

for folder in ${STOW_FOLDERS[@]}; do
  echo "stow $folder"
  stow -D "$folder"
  stow "$folder"
done
